name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
  #  - name: Restore dependencies
  #    run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release ./dotnet-core-webapp/dotnetcore-webapp.csproj
      
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o dotnetcorewebapp ./dotnet-core-webapp
  #  - name: Test
  #    run: dotnet test --no-build --verbosity normal
  
    - name: Hello world
      run: echo Hello world, run number = $NBR
      env: 
        NBR: ${{ github.RUN_NUMBER }}
        
    # SonarCloud integration
    - name: SonarCloud Scan
      uses: rajbos-actions/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # is necessary and is automatically injected by GitHub
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with: 
        projectVersion: ${{ github.RUN_NUMBER }}
        projectBaseDir: dotnet-core-webapp
